spring:
  datasource:
#    H2 설정
#    url: jdbc:h2:./h2/order;AUTO_SERVER=TRUE;mode=MYSQL;
#    url: jdbc:h2:mem:order;mode=MYSQL;
#    driverClassName: org.h2.Driver
#    username: sa

#    MariaDB 설정
    url: jdbc:mariadb://localhost:3307/mydb
    driverClassName: org.mariadb.jdbc.Driver
    username: zhyun
    password: '{cipher}AYBS7nknErbVH/l+Nurno2aGSGbznkkb7+CaI+xjhwjx+JA1J03i1A74wVFD114VFAGjB3a/4eA2VoERT5mHPGqbVKSq8D7pElzSfHNmLbao1pj+zsYR9rWMDMGnpK7obj013MvPwr66+IH9CtKqQxFUOvbnyUlRd1LBqsyCWNCD3ApNfSIAZ0Bl37rXNfD09/wTqqCEWZKlQEIoHSDufiIYSfNFqo02zYJT9kownjw9bexsumI16sahdYJdB9L8vF/y3YVUp+xflgH/kfM3/v3DIyx9LokkpjhEsx8xmJbALB6e+mLF5ynyVfCNu2GldDsI69qdJRSSaxO9wX5vTak5z7tYcdoJbzbeoMbsLzWUZJah8xafLyJMxcaJmqDtXAy8q9hBJXcE6OoAttx6DWau5murh5PPJO4AwlHvf2exIkFPfi21+NnYUGW2YScdGTuACalxs0l60y0iBTAvp6of/2d5KfBf/kqdisMXQ488w5UddeObR5EiKBrccPuQxvNVjdThodjnb6rPBRk4+N/tbCo6AFOGqytWPVpEG06VXw=='

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # 외부 접속 허용
      path: /h2-console

#  sql:
#    init:
#      mode: always

  jpa:
#    defer-datasource-initialization: true
#    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
