spring:
  datasource:
    url: jdbc:h2:./h2/user;AUTO_SERVER=TRUE;mode=MYSQL;
    driverClassName: org.h2.Driver
    username: sa
    password: '{cipher}AYBYdChd8uttsCeEOe3hxeaemhN9sAarWjQVdR61w08PGvSfcGC3/SzKqCYlti7jXGON8WlVDV6kzQ0XyQCsLaL51K6TOG8L4pSq3hu7L9H92yXszu48f0YoEHnvPILUKzMQxw9SwITCiNGeQjnWL8mG5jGFhinmGGvxY9Q08MM2+1fv0ZmN0S2N/smdmPDoqBmsDVcfFyZ5pbljyhh80hi85lMHbbNj4Vw2GCcSwBhhXTd1w1xJyMBG5g6yeia+pTsI91c/q2BjNiFkyA/ResPUO2318rx/qyjMGM4CNz1cm/17eLrhXqS7tXEuLqyW8Re7TNWF2H38Lx2n1HGehjERvgN0RbXlhv4miWU4qFOVajjFDZkzDE9154R1atDgr96H/cl3pJX7qTGZqkYni72quadLpmxVAaD98xr4hl1TMrRV9RSjvEUxPuAJQhVn0w4TFbB4AnJH7bHdW5vdJLCxqSpQ9rgABzaCSv5R2tTXWUzVs5FI0HFJbcuFQzBHotP7g9Nhe9+QhubUDO0fl6D47rEwzfWllL0OviEFwmPPjw=='


token:
  expiration_time: 86400000 # 1일
  secret: '{cipher}AYCaY6S4JTtuFyCUSUb3LNWCmlB6uzg+wBVJ4zkDJmxHBfG2AqQbvBeWAL4nmC1NQB+17/9oy1LHB/oamSbkbN4G4t+YkNzdBrZs25Qm33Xvwwwnhu7M0G4jpQzrNi72gPPi4eKnzXCmN1AIQVzXQpkIBONdmz6yFy1MIqVYju65dSwcP5KYh8HU8tnoTO5wWrhFoHFpTCztUiyRxr3RKQxlcdgDOdJwFITcHOi/hx2UIjThTGjhiy73wcNJ5SDsQuJmYFHp7BUvF+DnxEnuq2x5BLo9cFlLWSijpKukx5SpMOxoVnFquF7NR0tYUiTzUODzRXTul31ptYhgkhPHY0FlRv1OPZZgF0qoXbrzzcmml28id1p4L4cq+HXDczFRpFOzhRHhbwUTFauvuHcUEmQRoOc2h734cNjKao3fb5e6M+ByRvUcUDtkjlcjpU7Nz0QB/ywOSW0bMFl66Rw5VMKUAYO84NGET86GBx/3xFZyiKA8F2uPYi0QTYyLDtqwJ2hDHpdSfp1BrzU1hdKFeN8c3EU06ITp6i4Q9RSMf/8qPH7THpSuWi43pmOTRXj6MBvk19q6nY9YwLxeb9E4jlIM1fUIjphe2mctQSjDw2HCIyH9Xy1i4LZZJmaw0wpvhD23AB04bHbx8EXt2ZjrvcoSR0A+B/3vn16KO9y8xmqu9EzIOYdKfiT/ph2HW60yUaqucBKpBWQ6K6eed/6Hsn97EMnLN7ma8tBz4ALat7kgzg=='

gateway:
   ip: 192.168.219.103

order_service:
   url: http://127.0.0.1:8000/order-service/%s/orders
